<?php
$pageTitle='เส้นทางการเรียน'; $currentPage='learning-path.php';
require_once __DIR__.'/includes/guard.php';
$stmt=$pdo->prepare('SELECT * FROM learning_paths WHERE user_id=:uid ORDER BY updated_at DESC,id DESC');
$stmt->execute([':uid'=>$currentUser['id']]); $paths=$stmt->fetchAll();
?>
<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= htmlspecialchars($pageTitle) ?> - Next Beyond</title><link rel="stylesheet" href="../assets/css/output.css"></head><body class="bg-[#f4f7fb] text-navy-950"><div class="min-h-screen flex"><?php include 'includes/sidebar.php'; ?><div class="flex-1 ml-[240px] max-[960px]:ml-0"><?php include 'includes/topbar.php'; ?><main class="p-8 max-[640px]:p-4">
<?php if(!$paths): ?><div class="bg-white border border-[#e8ecf2] rounded-[20px] p-14 text-center"><h2 class="font-bold text-[18px] mb-2">ยังไม่มีแผนการเรียน</h2><p class="text-[#65738a]">เมื่อครูหรือระบบสร้างแผน แผนของคุณจะแสดงที่นี่</p></div><?php else: ?><div class="grid grid-cols-2 gap-5 max-[800px]:grid-cols-1"><?php foreach($paths as $path): $progress=min(100,(float)$path['progress_percent']); $steps=json_decode((string)$path['plan_data'],true); ?><article class="bg-white border border-[#e8ecf2] rounded-[20px] p-6"><span class="text-[12px] font-bold text-pink-500"><?= htmlspecialchars($path['subject']??'แผนการเรียน') ?></span><h2 class="font-black text-[19px] mt-2"><?= htmlspecialchars($path['target_goal']??'เป้าหมายของคุณ') ?></h2><p class="text-[13px] text-[#65738a] mt-1">ระดับ <?= htmlspecialchars($path['current_level']??'ทั่วไป') ?> · <?= (int)($path['hours_per_week']??0) ?> ชั่วโมง/สัปดาห์</p><div class="mt-5 h-3 rounded-full bg-[#edf2f7] overflow-hidden"><div class="h-full bg-pink-500" style="width:<?= $progress ?>%"></div></div><div class="text-right text-[12px] font-bold mt-2"><?= round($progress) ?>%</div><?php if(is_array($steps)): ?><div class="mt-4 space-y-2"><?php foreach(array_slice($steps,0,5) as $step): ?><div class="p-3 rounded-xl bg-[#f8fafc] text-[13px] font-medium"><?= htmlspecialchars(is_array($step)?($step['title']??'ขั้นตอนการเรียน'):(string)$step) ?></div><?php endforeach; ?></div><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?>
</main></div></div></body></html>
