<?php
$pageTitle = 'คำนวณคะแนน TCAS';
$currentPage = 'score-calculator.php';
require_once __DIR__ . '/includes/guard.php';

// Check if calculator is enabled in system settings
$stmt = $pdo->prepare("SELECT setting_value FROM system_settings WHERE setting_key = 'calculator_enabled'");
$stmt->execute();
$isEnabled = $stmt->fetchColumn();
if ($isEnabled === '0') {
    header('Location: index.php');
    exit;
}

// Fetch tracks from database
$stmt = $pdo->query("SELECT * FROM calculator_tracks WHERE is_active = 1 ORDER BY sort_order ASC, id ASC");
$tracks = $stmt->fetchAll();

// Define input fields mapping
$subjectLabels = [
    'tgat' => 'TGAT รวม (เต็ม 100)',
    'tpat' => 'TPAT (เต็ม 100)',
    'math1' => 'A-Level คณิต 1',
    'physics' => 'A-Level ฟิสิกส์',
    'english' => 'A-Level ภาษาอังกฤษ',
    'social' => 'A-Level สังคมศึกษา',
    'thai' => 'A-Level ภาษาไทย',
    'bio' => 'A-Level ชีววิทยา',
    'chem' => 'A-Level เคมี'
];

?>
<!DOCTYPE html>
<html lang="th">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?= htmlspecialchars($pageTitle) ?> - Next Beyond Academy</title>
  <link rel="stylesheet" href="../assets/css/output.css?v=<?= filemtime(__DIR__ . '/../assets/css/output.css') ?>">
  <link rel="stylesheet" href="../assets/css/student-portal.css?v=<?= filemtime(__DIR__ . '/../assets/css/student-portal.css') ?>">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
</head>
<body class="student-portal bg-[#f4f7fb] text-navy-950 font-sans antialiased">
<div class="min-h-screen flex">
  <?php include 'includes/sidebar.php'; ?>
  
  <div class="flex-1 flex flex-col ml-[240px] max-[1024px]:ml-0 min-w-0">
    <?php include 'includes/topbar.php'; ?>
    
    <main class="p-8 max-[640px]:p-4 max-w-4xl mx-auto w-full">
      <div class="bg-gradient-to-r from-pink-500 via-pink-600 to-pink-500 rounded-3xl p-6 sm:p-8 mb-8 shadow-pink">
        <div class="inline-flex items-center px-3 py-1 rounded-full bg-white/20 text-white text-xs font-semibold mb-3">
          <svg class="w-3.5 h-3.5 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"></path></svg> 
          คำนวณคะแนนรวม admission
        </div>
        <h1 class="text-2xl sm:text-3xl font-extrabold text-white">
          TCAS Score Calculator
        </h1>
        <p class="text-xs sm:text-sm text-pink-100 mt-2 max-w-2xl">
          คำนวณคะแนนตามค่าน้ำหนักจริงของแต่ละคณะ เพื่อประเมินโอกาสสอบติดและวางแผนเตรียมสอบ
        </p>
      </div>

      <?php if (empty($tracks)): ?>
        <div class="bg-white rounded-2xl p-10 text-center shadow-soft text-[#65738a]">
          <svg class="w-12 h-12 mx-auto mb-3 text-[#dce4ef]" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5"><path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
          <div class="font-bold text-lg mb-1 text-navy-950">ยังไม่มีข้อมูลกลุ่มคณะ</div>
          <p class="text-sm">แอดมินยังไม่ได้กำหนดกลุ่มคณะและสูตรคำนวณในระบบ</p>
        </div>
      <?php else: ?>
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
          
          <!-- Inputs (2/3) -->
          <div class="lg:col-span-2 bg-white rounded-2xl p-6 shadow-soft space-y-5 text-sm border border-[#e8ecf2]">
            <div>
              <label class="block text-navy-950 font-bold mb-2">เลือกกลุ่มคณะเป้าหมาย</label>
              <select id="facultyTrack" onchange="handleTrackChange()" class="w-full bg-[#f8fafc] border border-[#dce4ef] rounded-xl px-4 py-3 text-navy-950 font-medium focus:outline-none focus:border-pink-500 focus:ring-2 focus:ring-pink-500/20 transition-all">
                <?php foreach ($tracks as $index => $track): ?>
                  <option value="<?= $index ?>">
                    <?= htmlspecialchars($track['icon']) ?> <?= htmlspecialchars($track['name']) ?> (<?= htmlspecialchars($track['description']) ?>)
                  </option>
                <?php endforeach; ?>
              </select>
            </div>

            <div class="grid grid-cols-2 sm:grid-cols-3 gap-4 pt-2" id="score-inputs-container">
              <!-- Inputs will be dynamically generated by JS based on selected track -->
            </div>
          </div>

          <!-- Output Result (1/3) -->
          <div class="bg-navy-950 rounded-2xl p-6 shadow-soft flex flex-col justify-between text-center relative overflow-hidden">
            <div class="absolute top-0 right-0 -mr-8 -mt-8 w-32 h-32 rounded-full bg-indigo-500/10 blur-2xl"></div>
            <div class="absolute bottom-0 left-0 -ml-8 -mb-8 w-32 h-32 rounded-full bg-pink-500/10 blur-2xl"></div>
            
            <div class="relative z-10">
              <div class="text-xs font-bold uppercase tracking-wider text-[#94a3b8]">
                คะแนนรวมที่คำนวณได้
              </div>
              <div id="totalScoreOutput" class="font-sans text-5xl font-black text-white my-5">
                0.00%
              </div>
              <div id="chanceBadge" class="inline-flex items-center px-4 py-1.5 rounded-full text-xs font-bold bg-[#f1f5f9] text-[#65738a]">
                กรุณากรอกคะแนนเพื่อประเมิน
              </div>
              <p id="chanceAdvice" class="text-[12px] text-[#94a3b8] mt-5 leading-relaxed">
                เลือกกลุ่มคณะและกรอกคะแนนคาดหวังหรือคะแนนจริงในแต่ละวิชา
              </p>
            </div>

            <div class="mt-6 pt-5 border-t border-white/10 relative z-10">
              <a href="tests.php" class="w-full py-3 rounded-xl bg-pink-500 hover:bg-pink-600 transition-colors text-white font-bold text-sm flex items-center justify-center space-x-2 shadow-[0_4px_12px_rgba(231,45,130,0.25)]">
                <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"></path><path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                <span>ฝึกทำข้อสอบอัปคะแนน</span>
              </a>
            </div>
          </div>
        </div>
      <?php endif; ?>
    </main>
    <?php include 'includes/bottom-nav.php'; ?>
  </div>
</div>

<script>
const tracks = <?= json_encode($tracks, JSON_UNESCAPED_UNICODE) ?>;
const subjectLabels = <?= json_encode($subjectLabels, JSON_UNESCAPED_UNICODE) ?>;

function getWeights(track) {
    if (typeof track.weights === 'string') {
        try { return JSON.parse(track.weights); } catch (e) { return {}; }
    }
    return track.weights || {};
}

function handleTrackChange() {
    const select = document.getElementById('facultyTrack');
    if (!select || !tracks.length) return;
    const trackIndex = select.value;
    const track = tracks[trackIndex];
    if (!track) return;

    const weights = getWeights(track);
    const container = document.getElementById('score-inputs-container');
    container.innerHTML = '';

    // Generate input fields based on required subjects
    for (const subject in weights) {
        if (!weights[subject] || weights[subject] <= 0) continue;
        
        const label = subjectLabels[subject] || subject.toUpperCase();
        const weightPct = (weights[subject] * 100).toFixed(0);
        
        const div = document.createElement('div');
        div.innerHTML = `
            <label class="block text-navy-950 font-bold mb-1 flex items-center justify-between">
              <span class="truncate pr-2">${label}</span>
              <span class="text-[10px] text-pink-500 bg-pink-50 px-1.5 py-0.5 rounded shrink-0">${weightPct}%</span>
            </label>
            <input type="number" id="input-${subject}" data-subject="${subject}" min="0" max="100" step="0.01" class="score-input w-full bg-[#f8fafc] border border-[#dce4ef] rounded-lg px-3 py-2.5 text-navy-950 font-medium focus:outline-none focus:border-pink-500 focus:ring-2 focus:ring-pink-500/20 transition-all placeholder:text-[#cbd5e1]" placeholder="0.00" oninput="calculateScore()">
        `;
        container.appendChild(div);
    }
    
    // Attempt to restore previous values if possible, or leave empty
    calculateScore();
}

function calculateScore() {
    const select = document.getElementById('facultyTrack');
    if (!select || !tracks.length) return;
    const trackIndex = select.value;
    const track = tracks[trackIndex];
    const weights = getWeights(track);
    
    let total = 0;
    let allEmpty = true;
    
    for (const subject in weights) {
        if (!weights[subject] || weights[subject] <= 0) continue;
        const input = document.getElementById(`input-${subject}`);
        if (input && input.value !== '') {
            allEmpty = false;
            const val = parseFloat(input.value) || 0;
            total += val * weights[subject];
        }
    }

    const output = document.getElementById('totalScoreOutput');
    const badge = document.getElementById('chanceBadge');
    const advice = document.getElementById('chanceAdvice');
    const minScore = parseFloat(track.min_score) || 58;

    if (allEmpty) {
        output.innerText = '0.00%';
        badge.className = 'inline-flex items-center px-4 py-1.5 rounded-full text-xs font-bold bg-[#f1f5f9] text-[#65738a] border border-[#e8ecf2]';
        badge.innerHTML = 'กรุณากรอกคะแนนเพื่อประเมิน';
        advice.innerText = 'เลือกกลุ่มคณะและกรอกคะแนนคาดหวังหรือคะแนนจริงในแต่ละวิชา เพื่อดูโอกาสสอบติดของคุณ';
        return;
    }

    output.innerText = `${total.toFixed(2)}%`;

    if (total >= minScore + 5) {
        badge.className = 'inline-flex items-center px-4 py-1.5 rounded-full text-xs font-bold bg-green-500/20 text-green-400 border border-green-500/30';
        badge.innerText = '🎉 โอกาสสอบติด: สูงมาก';
        advice.innerText = 'คะแนนอยู่ในเกณฑ์ปลอดภัยสูงมาก แนะนำรักษามาตรฐานนี้ไว้และฝึกทำข้อสอบจับเวลาเพิ่มเติม';
    } else if (total >= minScore) {
        badge.className = 'inline-flex items-center px-4 py-1.5 rounded-full text-xs font-bold bg-amber-500/20 text-amber-400 border border-amber-500/30';
        badge.innerText = '⚖️ โอกาสสอบติด: ปานกลาง มีลุ้น';
        advice.innerText = `คะแนนปริ่มเกณฑ์ขั้นต่ำของปีก่อน (${minScore.toFixed(2)}%) ควรเร่งทำคะแนนเพิ่มในวิชาที่ค่าน้ำหนักสูงเพื่อความอุ่นใจ`;
    } else {
        badge.className = 'inline-flex items-center px-4 py-1.5 rounded-full text-xs font-bold bg-red-500/20 text-red-400 border border-red-500/30';
        badge.innerText = '⚠️ โอกาสสอบติด: มีความเสี่ยง';
        advice.innerText = `คะแนนยังต่ำกว่าเกณฑ์เฉลี่ย (${minScore.toFixed(2)}%) เร่งทบทวนเนื้อหาและฝึกทำข้อสอบอย่างเข้มข้นด่วน!`;
    }
}

// Initialize
if (document.getElementById('facultyTrack')) {
    handleTrackChange();
}
</script>
</body>
</html>
